# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.securisation-transport
canonical: https://interop.esante.gouv.fr/ig/securisation-transport # the last part of canonical and id must be the same
name: IG-securisation-transport-api-rest
title: Sécurisation de la couche transport API REST
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
version: 1.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    principes_generaux_du_volet.md:
        title: Principes généraux de ce volet
        archi_documentaire.md:
            title: Architecture documentaire
        standards.md:
            title:  Standards d'échange
        principes_securisation.md:
            title: Principes de sécurisation
    api_prosanteconnectee.md:
        title: API ProSantéConnectée
        api_prosanteconnectee_web.md:
            title: Appel d'une API ProSantéConnectée depuis une application web
        api_prosanteconnectee_web_erreurs.md:
            title: Appel d'une API ProSantéConnectée depuis une application web - cas d'erreurs
        api_prosanteconnectee_client_lourd.md:
            title: Appel d'une API ProSantéConnectée depuis une application client lourd ou mobile
        api_prosanteconnectee_userinfo.md:
            title: Récupération et utilisation du jeton userinfo PSC
        api_prosanteconnectee_donnees_metiers.md:
            title: Appel d'une API ProSantéConnectée avec des données métiers complémentaires
    glossaire.md:
        title:  Glossaires
    documents_de_reference.md:
        title: Documents de référence
 
 
    about.md:
        title: A propos de ce guide
        

menu:
    Accueil: index.html
    Description générale des flux:
        Principes généraux de ce volet : principes_generaux_du_volet.html
        Architecture documentaire : archi_documentaire.html
        Standards utilisés (REST, OAUTH 2.0 ET OIDC) : standards.html
        Principes de sécurisation : principes_securisation.html
    API ProSantéConnectée: 
        Description générale : api_prosanteconnectee.html
        Application web : api_prosanteconnectee_web.html
        Application web - cas d'erreurs : api_prosanteconnectee_web_erreurs.html
        Application client lourd ou mobile : api_prosanteconnectee_client_lourd.html
        Récupération et utilisation du jeton userinfo PSC : api_prosanteconnectee_userinfo.html
        Passage de données métiers de l'application cliente vers l'API  : api_prosanteconnectee_donnees_metiers.html
    Glossaire et documents de référence:  
        Glossaire: glossaire.html
        Documents de référence: documents_de_reference.html

    A propos de ce guide: about.html