# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.securisation-transport
canonical: https://interop.esante.gouv.fr/ig/securisation-transport # the last part of canonical and id must be the same
name: IG-securisation-transport-api-rest
title: Sécurisation de la couche transport API REST
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    specifications_techniques.md:
        construction_des_flux.md:
        st_flux1.md:
            title: Flux 01
        st_flux2.md:
            title: Flux 02
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
        archi_documentaire.md:
            title: Architecture documentaire
        standards.md:
            title:  Standards d'échange
        glossaire.md:
            title:  Glossaires
 
    about.md:
        title: A propos de ce guide
        

menu:
    Accueil: index.html
    Description générale des flux:
        Architecture documentaire : archi_documentaire.html
        Standards utilisés : standards.html
    Glossaire :   glossaire.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Documentation sur les IG": new-tab https://interop.esante.gouv.fr/ig/documentation/
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html